version: '3.8'
services:
  web:
    image: php:8.2-apache
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    command: >
      bash -c "docker-php-ext-install pdo pdo_mysql &&
               a2enmod rewrite &&
               apache2-foreground"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: kapelnica_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      
  tg_bot:
    image: php:8.2-cli
    container_name: kapelnica-med-bot-1
    working_dir: /var/www/html/backend
    volumes:
      - .:/var/www/html
    command: >
      bash -c "docker-php-ext-install pdo pdo_mysql &&
               php bot.php"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

volumes:
  db_data:

